function(feelpp_get_compile_definition varTarget varValue )
  get_property(CD TARGET ${varTarget} PROPERTY INTERFACE_COMPILE_DEFINITIONS)
  list(FIND CD "${varValue}" res)
  if ( NOT res EQUAL -1 )
    set(${varValue} ${res} PARENT_SCOPE )
  endif()
endfunction()

function(feelpp_set_options varTarget prefix key )
  get_property(CD TARGET ${varTarget} PROPERTY INTERFACE_COMPILE_DEFINITIONS)
  foreach( opts IN LISTS CD )
    string( REGEX MATCH "${prefix}_${key}_[a-zA-Z0-9_]+$" OPT ${opts} )
    if ( OPT )
      #message("OPT = ${OPT}")
      set(${OPT} 1 PARENT_SCOPE)
    endif()
  endforeach()
endfunction()
